name: write_story
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  
  # main package
  flutter_quill:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      ref: master

  # ui
  lottie: ^1.0.1
  page_transition: ^2.0.1-nullsafety.0
  photo_view: ^0.11.1
  animated_clipper: ^0.2.0
  flutter_speed_dial: ^3.0.5

  # State management
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1

  # local storage
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.1.0
  encrypt: ^5.0.0-beta.1

  # network
  csv: ^5.0.0
  dio: ^4.0.0-prev3
  googleapis: ^2.0.0
  http: ^0.13.1

  flutter_image_compress: ^1.0.0
  flutter_cache_manager: ^3.0.1
  cached_network_image: ^3.0.0
  permission_handler: ^6.1.1

  # google services
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  google_sign_in: ^5.0.1

  # functionalities
  in_app_update: ^2.0.0
  url_launcher: ^6.0.2
  vibration: ^1.7.4-nullsafety.0
  launch_review: ^3.0.1
  share: ^2.0.1
  scroll_to_index: ^2.0.0

  get_version:
    git:
      url: git@github.com:theacheng/get_version.git
      ref: master

  image_gallery_saver:
    git:
      url: git@github.com:theacheng/image_gallery_saver.git
      ref: master
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/translations/
    - assets/database/write_story.db
    
    # Ref: https://iconscout.com/illustration/thinking-woman-1840996
    - assets/illustrations/thinking-woman.png
    - assets/illustrations/

    # Book Ref: https://assets1.lottiefiles.com/packages/lf20_wh5alaq6.json
    - assets/animations/

    - assets/flags/
    - assets/icons/
    - assets/emoji-64/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Black.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BlackItalic.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BoldItalic.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBold.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBoldItalic.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Italic.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Medium.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-MediumItalic.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBold.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBoldItalic.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy/Kantumruy-Light.ttf
        - asset: assets/fonts/Kantumruy/Kantumruy-Regular.ttf
        - asset: assets/fonts/Kantumruy/Kantumruy-Bold.ttf
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang/Battambang-Bold.ttf
        - asset: assets/fonts/Battambang/Battambang-Regular.ttf
    - family: Bokor
      fonts:
        - asset: assets/fonts/Bokor/Bokor-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
